export const URL = 'https://debtmanagement.runasp.net'
// export const URL = 'https://localhost:7264'

export const MODE = {
  ADD: 'Add',
  UPDATE: 'Update',
}

export const TRANSACTION_TYPE_ID = {
  PAYMENT: 1,
  WITHDRAW: 2,
}
export const TRANSACTION_TYPE_NAME = {
  PAYMENT: 'Payment',
  WITHDRAW: 'Withdrawal',
}

export const PAYMENT_Date = {
  OLD: 'Old',
  TODAY: 'ToDay',
  CLOSER: 'Closer',
}

export const REACT_QUERY_NAME = {
  SUPPLIERS: 'suppliersTable',
  CLIENTS: 'clientsTable',
  USER_TRANSACTIONS: 'userTransactionsTable',
  CLIENT_TRANSACTIONS: 'clientTransactionsTable',
  SUPPLIER_TRANSACTIONS: 'supplierTransactionsTable',
  CLIENTS_PAYMENTDATE: 'clientPaymentDatesTable',
  SUPPLIERS_PAYMENTDATE: 'supplierPaymentDatesTable',
}

export const ORDER_PERSON_BY = {
  DEFAULT: 'Default',
  NAME: 'Name',
  OLDER_PAYMENT_DATES: 'OlderPaymentDates',
  CLOSER_PAYMENT_DATES: 'CloserPaymentDates',
  LARGEST_AMOUNT: 'LargestTotalAmount',
  SMALLEST_AMOUNT: 'SmallestTotalAmount',
}

export const PDF = {
  MARGIN: {
    LEFT: 14,
    TOP_3: 3,
    TOP_5: 5,
    TOP_7: 7,
    TOP_10: 10,
    TOP_20: 20,
  },
  TEXT: {
    I_GAVE: 'I Gave',
    I_GOT: 'I Got',
    GLOBAL_BALANCE: 'Balance',
    APP_LOGO: 'Daftari',
    STORE: 'Store',
    PHONE: 'Phone',
    USER: 'User',
    CLIENT: 'Client',
    SUPPLIER: 'Supplier',
    FOOTER: 'Generated by Daftari Management System',
  },
}

export const UI = {
  TEXT: {
    I_GAVE: 'I Gave',
    I_GOT: 'I Got',
    GLOBAL_BALANCE: 'Global Balance',
  },
  HEADER: {
    CLIENTS: 'Clients',
    SUPPLIERS: 'Suppliers',
    CLIENTS_PAYMENTDATE: 'Clients PaymentDates',
    SUPPLIERS_PAYMENTDATE: 'Suppliers PaymentDates',
    CLIENTS_TRANSACTIONS: 'Clients Transactions',
    SUPPLIERS_TRANSACTIONS: 'Suppliers Transactions',
    USERS_TRANSACTIONS: 'My Transactions',
  },
}
