export const MODE = {
  ADD: 'Add',
  UPDATE: 'Update',
}

export const TRANSACTION_TYPE_ID = {
  PAYMENT: 1,
  WITHDRAW: 2,
}
export const TRANSACTION_TYPE_NAME = {
  PAYMENT: 'Payment',
  WITHDRAW: 'Withdrawal',
}

export const PAYMENT_Date = {
  OLD: 'Old',
  TODAY: 'ToDay',
  CLOSER: 'Closer',
}

export const REACT_QUERY_NAME = {
  SUPPLIERS: 'suppliersTable',
  CLIENTS: 'clientsTable',
  USER_TRANSACTIONS: 'userTransactionsTable',
  CLIENT_TRANSACTIONS: 'clientTransactionsTable',
  SUPPLIER_TRANSACTIONS: 'supplierTransactionsTable',
  CLIENTS_PAYMENTDATE: 'clientPaymentDatesTable',
  SUPPLIERS_PAYMENTDATE: 'supplierPaymentDatesTable',
}

export const UI_TEXT = {
  I_GIVE: 'I Give',
  I_GET: 'I Get',
}

export const ORDER_PERSON_BY = {
  DEFAULT: 'default',
  NAME: 'Name',
  OLDER_PAYMENT_DATES: 'OlderPaymentDates',
  CLOSER_PAYMENT_DATES: 'CloserPaymentDates',
  LARGEST_AMOUNT: 'LargestTotalAmount',
  SMALLEST_AMOUNT: 'SmallestTotalAmount',
}

export const PDF = {
  marginLeft: 14,
  marginTop_3: 3,
  marginTop_7: 7,
  marginTop_5: 5,
  marginTop_10: 10,
  marginTop_20: 20,
  footer: 'Generated by Daftari Management System',
}
